import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "../../tailwind-base.css";

import "./globals.css";

// import { Heebo } from 'next/font/google'

// export const heeboFont = Heebo({
//   subsets: ['latin', 'hebrew'],
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
//   variable: '--font-heebo',
//   display: 'swap'
// })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
